words = {
    'lang-uz': "Assalomu alaykum, tilni tanlang 👇",
    'welcome-uz': "Assalomu alaykum, xush kelibsiz!",
    'welcome-ru': "Здравствуйте, добро пожаловать!",
    'name-uz': "Ismingizni kiriting: ",
    'name-ru': "Введите свое имя: ",
    'phone-uz': "Telefon raqamingizni kiriting: ",
    'phone-ru': "Введите свой номер телефона: ",
    'company-uz': "Siz ishlayotgan kompaniya yoki tashkilot nomi: ",
    'company-ru': "Название компании или организации, в которой вы работаете: ",
    'skip-uz': "O'tkazib yuborish",
    'skip-ru': "Пропустить",
    'registered-uz': "Siz muvaffaqiyatli ro'yxatdan o'tdingiz",
    'registered-ru': "Вы успешно зарегистрировались",
    "tabriknomalar-uz": "Tabriknomalar",
    "tabriknomalar-ru": "Открытки",
    "devor-uz": "Devor uchun",
    "devor-ru": "Для стены",
    "bayram-uz": "Bayramlar",
    "bayram-ru": "Праздники",
    "toy-uz": "To'y",
    "toy-ru": "Свадьба",
    "yubiley-uz": "Yubiley",
    "yubiley-ru": "Юбилейный",
    "tugilgan-uz": "Tug'ilgan kun",
    "tugilgan-ru": "День рождения",
    "choose-event-uz": "Qanday tadbir uchun?",
    "choose-event-ru": "На какое мероприятие?",
    'yangiyil-uz':'Yangi yil',
    'yangiyil-ru':'Новый год',
    'xotira-uz':'Xotira va qadirlash kuni',
    'xotira-ru':'день памяти и признательности',
    'mustaqil-uz':'Mustaqillik kuni',
    'mustaqil-ru':'День независимости',
    'ustoz-uz':"O'qituvchi va murabbiylar kuni",
    'ustoz-ru':'День учителей и тренеров',
    'konsitutsiya-uz':'Konsitutsiya kuni',
    'konsitutsiya-ru':'День Конституции',
    'ramazon-uz':'Ramazon hayiti',
    'ramazon-ru':'Рамадан Ид',
    'qurbon-uz':'Qurbon hayiti',
    'qurbon-ru':'Ид аль-Адха',
    'qizlar-uz':'Xalqaro xotin-qizlar kuni',
    'qizlar-ru':'Международный женский день',
    'navruz-uz':"Navro'z bayrami",
    'navruz-ru':'праздник Навруз',
    'vatan-uz':'Vatan himoyachilar kuni',
    'vatan-ru':'День защитника Отечества',
    'ayol-uz':'Ayol',
    'ayol-ru':'Женщина',
    'erkak-uz':'Erkak',
    'erkak-ru':'Мужской',
    'bola-uz':'Bolakay',
    'bola-ru':'Мальчик',
    'qz-uz':'Qizaloq',
    'qz-ru':'Девочка',
    'forwho-uz':'Kim uchun',
    'forwho-ru':'Для кого',
}