words = {
    'lang-uz': "Assalomu alaykum, tilni tanlang 👇",
    'welcome-uz': "Assalomu alaykum, xush kelibsiz!",
    'welcome-ru': "Здравствуйте, добро пожаловать!",
    'name-uz': "Ismingizni kiriting: ",
    'name-ru': "Введите свое имя: ",
    'phone-uz': "Telefon raqamingizni kiriting: ",
    'phone-ru': "Введите свой номер телефона: ",
    'company-uz': "Siz ishlayotgan kompaniya yoki tashkilot nomi: ",
    'company-ru': "Название компании или организации, в которой вы работаете: ",
    'skip-uz': "O'tkazib yuborish",
    'skip-ru': "Пропустить",
    'registered-uz': "Siz muvaffaqiyatli ro'yxatdan o'tdingiz",
    'registered-ru': "Вы успешно зарегистрировались",
}